### ISSUE TITLE
AddToVGPS does not show anymore

### ISSUE THREAD

**Issue by jonashogstrom** [ganja1447/greasemonkey-geocaching-projectgc#33]
The very handy combobox in the right hand menu "Add to VGPS" does not show anymore when I load cache pages. I can't see any reason in the code why it doesn't. It should add the code like this:

  $('div.CacheDetailNavigation ul:first').append(html);

and as far as I can see, the div is still called CacheDetailNavigation. tried it in both FF and Chrome. 

I tried to figure out how to debug the script, but I couldnt find it in either the chrome debugger or in firebug :( Other features from the script is working like usual, such as the FP-extensions.

**Comment by ganja1447** [comment]
The script broke at "Add PGC Map links", because the div where we got the coordinates from didn't exist. Geocaching.com has removed the "other conversions" div.
"Resolve the coordinates into an address" didn't work either, same reason. When these didn't work, it didn't get as far as to "Add VGPS".
